config/routes.rb
Rails.application.routes.draw do
  root 'naptips#index'
  resources :naptips
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/naptip.rb
class Naptip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/naptips_controller.rb
class NaptipsController < ApplicationController
    def index
        @naptips = Naptip.first
    end

    def new
        @naptips = Naptip.new
    end

    def create
        Naptip.create
        redirect_to root_path
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/naptips_helper.rb
module NaptipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodingChallenge1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/naptips/index.html.erb
<h1>Nap App.</h1>
<h2>Here's some tips for the perfect power nap:</h2>
<br />
<h1><%= @naptip.inspect %></h1>
<br />

<%= link_to 'Click here to submit tips for better sleep.', new_naptip_path %>

app/views/naptips/new.html.erb
<h1>How do you sleep at night?</h1>
<%= simple_form_for @naptips do |f| %>
  <%= f.input :sleep_tip %>
  <%= f.submit 'Create', class: 'btn btn-danger' %>
<% end %>